<script src="https://giscus.app/client.js"
        data-repo="TheRealDuckers/site"
        data-repo-id="R_kgDOQom_YQ"
        data-category="General"
        data-category-id="DIC_kwDOQom_Yc4Cz7Yg"
        data-mapping="specific"
        data-term="Guest Book"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="dark_tritanopia"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
